<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" Version="4.0.1" />
    <ProjectReference Include="../../src/Schematic.Supertest/Schematic.Supertest.csproj" />
  </ItemGroup>
</Project>
